---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-nginx
  namespace: hello-world-nginx
  labels:
    app: hello-world-nginx
    version: "1.0"
    
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-world-nginx
  template:
    metadata:
      labels:
        app: hello-world-nginx
        version: "1.0"
    spec:
      containers:
      - name: hello-world
        image: nginxdemos/hello
        ports:
        - containerPort: 80
          name: http
        env:
        - name: PORT
          value: "80"
        - name: TARGET
          value: "World"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-nginx-service
  namespace: hello-world-nginx
  labels:
    app: hello-world-nginx
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
    # nodePort: 30080  # Optional: specify port (30000-32767 range)
  selector:
    app: hello-world-nginx

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-world-nginx-ingress
  namespace: hello-world-nginx
  labels:
    app: hello-world-nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: hello-world-nginx.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hello-world-nginx-service
            port:
              number: 80

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-world-nginx-config
  namespace: hello-world-nginx
  labels:
    app: hello-world-nginx
data:
  message: "Hello from Kubernetes deployed via Harness!"
  environment: "demo"

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hello-world-nginx-hpa
  namespace: hello-world-nginx
  labels:
    app: hello-world-nginx
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hello-world-nginx
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
